travis:
  secure:
    BINSTAR_TOKEN: BBqN49OF5qlrr4e5zJef35QFB/+Ht1kCPvolKPvD3coFTgRt1JWy3JBvgNiSZ3i32b72NLi98EvxIaFqgTTxrw48kzrM3ijdtCHbFNmRQdKRP1Nvykj6sEH8JeNii98D4HQ9IvauMabZFE7qK1X5qGZStWSJG2NHRt0qgxz83zfO4bnEO6ZxVY9Nf3096NZRnOYkcJpo79iPTt4ke2A1vUhohJT6SR9qJg16I1xH5/FgQDmUPPIIpMs+Vy2BNO/LaYdOF0/Lkkpq6n2n7oJwDiKmeEfORkZtSQe7GIWQujmhIMjavQxwzxN5Caz8HMuj4XL4YhgAbKQjvoW45ChY+fE50IDDXcJfRH2JqGaYW+/Mb92thhCexp0MamMsntg0nYLgCP4jkZ9uREEMuwTwJnMdNMEdQxHTb1rpzcE01mjf+/gw3bzHfxSLsGZSYVQe6p2xv/QPD+dP+SgRMO4yM62+PDFaGj1Vd02i23/lpQHmHMnbP8CFO6uXH1/ZLIFPIdjkpZHvKCuIq36asfTtEnwimFjlhV35reO6ZzBeAxgmJQi3cZGRSwUzff1QU4ZVp7gp781J2PB1P27rmSvqqpdWZe8brepmaUjnPLEDv1ElHQiPehxqzKMw0rYwjMzuzVo5cC1j5PB3P0YbwyDHoIFUB/U5mHOdOppTYeZ+7Es=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
